name: CI

on:
  push:
    paths-ignore:
      - 'documents/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]
    concurrency: ci-${{ github.ref }}
    env:
      working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Setup dependencies
      working-directory: ${{env.working-directory}}
      run: npm install
    - name: Unit Test
      working-directory: ${{env.working-directory}}
      run: npm run test
